# Generated by Django 6.0.6 on 2026-07-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="Дата платежа"),
        ),
    ]
