# Generated by Django 6.0.6 on 2026-07-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_payment_is_paid_payment_stripe_payment_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Ссылка на оплату Stripe",
            ),
        ),
    ]
