# Generated by Django 6.0.6 on 2026-06-21 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название курса",
                        max_length=100,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="previews/courses/",
                        verbose_name="Превью (картинка)",
                    ),
                ),
                ("description", models.TextField(verbose_name="Краткое описание")),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название урока",
                        max_length=100,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите краткое описание урока",
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="previews/lessons/",
                        verbose_name="Превью (картинка)",
                    ),
                ),
                (
                    "video_link",
                    models.URLField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Ссылка на видео урока",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Укажите к какому курсу относится урок",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="core.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
