# Generated by Django 6.0.6 on 2026-07-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(
                default=100, verbose_name="Цена (в рублях)"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.PositiveIntegerField(
                default=100, verbose_name="Цена (в рублях)"
            ),
        ),
    ]
