# Generated by Django 6.0.6 on 2026-07-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_course_price_lesson_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_update_notification_date",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Дата последнего уведомления об обновлении",
            ),
        ),
    ]
